# 端口号
server:
  port: 9000

# 应用名称
spring:
  application:
    name: register-service

eureka:
  server:
    peer-node-read-timeout-ms: 5000 #默认200
    # 配置是否开启Eureka自我保护模式（测试使用）
    enable-self-preservation: true
    # 扫描失效服务的间隔时间（单位毫秒，默认是60*1000）即60秒
    eviction-interval-timer-in-ms: 4000
    # 自我保护系数 默认 0.85
    renewal-percent-threshold: 0.49
  instance:
    #主机名称
    hostname: ${spring.cloud.client.ip-address}
    #使用IP注册，而不是主机名称  unavailable-replicas
    prefer-ip-address: true
    #instance id显示
    instance_id: ${spring.cloud.client.ip-address}:${server.port}
    #心跳时间，默认30second
    lease-renewal-interval-in-seconds: 30
    #剔除服务时间，默认90second
    lease-expiration-duration-in-seconds: 90
    metadata-map:
      user.name: ${spring.security.user.name}
      user.password: ${spring.security.user.password}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone:  http://${eureka.instance.hostname}:${server.port}/eureka/